
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: spark-cluster
  region: eu-west-2
  version: "1.20"
availabilityZones:
- eu-west-2a
- eu-west-2b
managedNodeGroups:
- name: managed-nodes
  labels:
    role: managed-nodes
  instanceType: t2.micro
  minSize: 1
  maxSize: 10
  desiredCapacity: 1
  volumeSize: 20