
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: spark-cluster
  region: eu-west-2
  version: "1.23"
vpc:
  subnets:
    private:
      eu-west-2a: { id: subnet-0dc2e42de958c87c9 }
      eu-west-2b: { id: subnet-05ec02d15637ed38c }
#availabilityZones:
#- eu-west-2a
#- eu-west-2b
managedNodeGroups:
- name: managed-nodes
  labels:
    role: managed-nodes
  instanceType: t2.micro
  minSize: 1
  maxSize: 10
  desiredCapacity: 1
  volumeSize: 20