#
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  POSTGRES_DB: bXRhX2RhdGE=   #mta_data
  POSTGRES_USER: cG9zdGdyZXM=   #postgres cG9zdGdyZXM=
  POSTGRES_PASSWORD: YWRtaW4xMjM=     #admin123