apiVersion: v1
kind: Service # Create service
metadata:
  name: postgres # Sets the service name
  namespace: default
  #namespace: spark-and-postgres
  labels:
    app: postgres # Defines app to create service for
spec:
  #type: NodePort # Sets the service type
  ports:
    - protocol: TCP
      port: 31653
      targetPort: 5432
  selector:
    app: postgres


