#create a PostgreSQL deployment and declare Pods configuration for the PostgreSQL in Kubernetes.
#This PostgreSQL manifest for deployment of PostgreSQL container uses PostgreSQL 10.4 image. 
#It uses PostgreSQL configuration like username, password, database name from the configmap. 
#It also mounts the volume created from the persistent volumes and claims to make PostgreSQL container’s data persists.

apiVersion: apps/v1
kind: Deployment # Create a deployment
metadata:
  name: postgres # Set the name of the deployment
  namespace: default
  #namespace: spark-and-postgres
spec:
  replicas: 1 # Set deployment replicas
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine  # Docker image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432  # Exposing the container port 5432 for PostgreSQL client connections.
          envFrom:
            - configMapRef:
                name: postgres-config  # Using the ConfigMap postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim