kind: Service
apiVersion: v1
metadata:
  name: spark
  #namespace: spark-and-postgres
  labels:
    app: spark # Defines app to create service for
spec:
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
    - name: spark
      port: 7077
      targetPort: 7077
  selector:
    app: spark